CREATE PROC SP_INS_GV_KT_MSHH
    @MSGV INT, 
	@TENGV NVARCHAR(30), 
	@SODT VARCHAR(10),
    @DIACHI NVARCHAR(50), 
	@MSHH INT, 
	@NAMHH SMALLDATETIME
AS
BEGIN
    IF NOT EXISTS (SELECT MSHH FROM HOCHAM WHERE MSHH = @MSHH)
        RETURN 0
    INSERT INTO GIAOVIEN VALUES (@MSGV, @TENGV, @DIACHI, @SODT, @MSHH, @NAMHH)
    RETURN 1
END;
GO

