CREATE   PROCEDURE SP_UPD_DETAI_KT_MSDT
    @MSDT char(6),
    @TENDT NVARCHAR(30)
AS
BEGIN
    IF NOT EXISTS (SELECT MSDT FROM DETAI WHERE MSDT = @MSDT)
    BEGIN
        RETURN 0; -- Nếu MSHH chưa tồn tại trả về 0
    END

    UPDATE DETAI
    SET TENDT = @TENDT
    WHERE MSDT = @MSDT
    RETURN 1
END;
GO

