
CREATE FUNCTION f_DanhSachSVThucHienDeTai (@MSDT char(6))
RETURNS TABLE
AS
RETURN (
    SELECT
        SV.MSSV,
        SV.TENSV
    FROM SINHVIEN SV
    JOIN SV_DETAI SD ON SV.MSSV = SD.MSSV
    WHERE SD.MSDT = @MSDT
);
GO

