CREATE TABLE [dbo].[DETAI_DIEM] (
    [MSDT]    CHAR (6)      NOT NULL,
    [DIEMTB]  FLOAT (53)    NULL,
    [XEPLOAI] NVARCHAR (20) NULL,
    PRIMARY KEY CLUSTERED ([MSDT] ASC)
);
GO

ALTER TABLE [dbo].[DETAI_DIEM]
    ADD CONSTRAINT [FK_DETAI_DIEM_DETAI] FOREIGN KEY ([MSDT]) REFERENCES [dbo].[DETAI] ([MSDT]);
GO

