CREATE TABLE [dbo].[GIAOVIEN] (
    [MSGV]   INT           NOT NULL,
    [TENGV]  NVARCHAR (30) NOT NULL,
    [DIACHI] NVARCHAR (50) NOT NULL,
    [SODT]   VARCHAR (10)  NOT NULL,
    [MSHH]   INT           NOT NULL,
    [NAMHH]  SMALLDATETIME NOT NULL,
    PRIMARY KEY CLUSTERED ([MSGV] ASC)
);
GO

ALTER TABLE [dbo].[GIAOVIEN]
    ADD CONSTRAINT [FK_GV_HH] FOREIGN KEY ([MSHH]) REFERENCES [dbo].[HOCHAM] ([MSHH]);
GO

