CREATE TABLE [dbo].[GV_HV_CN] (
    [MSGV] INT           NOT NULL,
    [MSHV] INT           NOT NULL,
    [MSCN] INT           NOT NULL,
    [NAM]  SMALLDATETIME NOT NULL,
    PRIMARY KEY CLUSTERED ([MSGV] ASC, [MSHV] ASC, [MSCN] ASC)
);
GO

ALTER TABLE [dbo].[GV_HV_CN]
    ADD CONSTRAINT [FK_GV_HV_CN_GV] FOREIGN KEY ([MSGV]) REFERENCES [dbo].[GIAOVIEN] ([MSGV]);
GO

ALTER TABLE [dbo].[GV_HV_CN]
    ADD CONSTRAINT [FK_GV_HV_CN_CN] FOREIGN KEY ([MSCN]) REFERENCES [dbo].[CHUYENNGANH] ([MSCN]);
GO

ALTER TABLE [dbo].[GV_HV_CN]
    ADD CONSTRAINT [FK_GV_HV_CN_HV] FOREIGN KEY ([MSHV]) REFERENCES [dbo].[HOCVI] ([MSHV]);
GO

