CREATE TABLE [dbo].[GV_PBDT] (
    [MSGV] INT        NOT NULL,
    [MSDT] CHAR (6)   NOT NULL,
    [DIEM] FLOAT (53) NOT NULL,
    PRIMARY KEY CLUSTERED ([MSGV] ASC, [MSDT] ASC)
);
GO

ALTER TABLE [dbo].[GV_PBDT]
    ADD CONSTRAINT [FK_GV_PBDT_DT] FOREIGN KEY ([MSDT]) REFERENCES [dbo].[DETAI] ([MSDT]);
GO

ALTER TABLE [dbo].[GV_PBDT]
    ADD CONSTRAINT [FK_GV_PBDT_GV] FOREIGN KEY ([MSGV]) REFERENCES [dbo].[GIAOVIEN] ([MSGV]);
GO

