CREATE TABLE [dbo].[HOIDONG] (
    [MSHD]      INT           NOT NULL,
    [PHONG]     INT           NOT NULL,
    [TGBD]      SMALLDATETIME NOT NULL,
    [NGAYHD]    SMALLDATETIME NOT NULL,
    [TINHTRANG] NVARCHAR (30) NULL,
    [MSGV]      INT           NULL,
    PRIMARY KEY CLUSTERED ([MSHD] ASC)
);
GO

ALTER TABLE [dbo].[HOIDONG]
    ADD CONSTRAINT [FK_HD_GV] FOREIGN KEY ([MSGV]) REFERENCES [dbo].[GIAOVIEN] ([MSGV]);
GO

