CREATE TABLE [dbo].[HOIDONG_DT] (
    [MSHD]      INT        NOT NULL,
    [MSDT]      CHAR (6)   NOT NULL,
    [QUYETDINH] NCHAR (10) NULL
);
GO

ALTER TABLE [dbo].[HOIDONG_DT]
    ADD CONSTRAINT [FK_HD_DT_DT] FOREIGN KEY ([MSDT]) REFERENCES [dbo].[DETAI] ([MSDT]);
GO

ALTER TABLE [dbo].[HOIDONG_DT]
    ADD CONSTRAINT [FK_HD_DT_HD] FOREIGN KEY ([MSHD]) REFERENCES [dbo].[HOIDONG] ([MSHD]);
GO

ALTER TABLE [dbo].[HOIDONG_DT]
    ADD CONSTRAINT [PK_HD_DT] PRIMARY KEY CLUSTERED ([MSHD] ASC, [MSDT] ASC);
GO

