CREATE TABLE [dbo].[HOIDONG_GV] (
    [MSHD] INT NOT NULL,
    [MSGV] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([MSHD] ASC, [MSGV] ASC)
);
GO

ALTER TABLE [dbo].[HOIDONG_GV]
    ADD CONSTRAINT [FK_HD_GV_HD] FOREIGN KEY ([MSHD]) REFERENCES [dbo].[HOIDONG] ([MSHD]);
GO

ALTER TABLE [dbo].[HOIDONG_GV]
    ADD CONSTRAINT [FK_HD_GV_GV] FOREIGN KEY ([MSGV]) REFERENCES [dbo].[GIAOVIEN] ([MSGV]);
GO

