CREATE TABLE [dbo].[SV_DETAI] (
    [MSSV] CHAR (8) NOT NULL,
    [MSDT] CHAR (6) NOT NULL,
    PRIMARY KEY CLUSTERED ([MSSV] ASC, [MSDT] ASC)
);
GO

ALTER TABLE [dbo].[SV_DETAI]
    ADD CONSTRAINT [FK_SV_DETAI_DT] FOREIGN KEY ([MSDT]) REFERENCES [dbo].[DETAI] ([MSDT]);
GO

ALTER TABLE [dbo].[SV_DETAI]
    ADD CONSTRAINT [FK_SV_DETAI_SV] FOREIGN KEY ([MSSV]) REFERENCES [dbo].[SINHVIEN] ([MSSV]);
GO

