-- GRANT

GRANT INSERT ON DETAI TO U3;
GRANT INSERT ON HOIDONG TO U3;
GRANT INSERT ON GV_HDDT TO U3;
GO

-- INSERT trên HOIDONG

EXECUTE AS USER = 'U3';
INSERT INTO HOIDONG (MSHD, PHONG, TGBD, NGAYHD, TINHTRANG, MSGV) VALUES
(4, 2, '07:00', '2014-11-29', N'Thật', 201);
REVERT;
GO

-- Kiểm tra

SELECT * FROM HOIDONG;
GO
