-- REVOKE

REVOKE INSERT ON HOIDONG FROM U3;
GO

-- Kiểm tra

EXECUTE AS USER = 'U3';
INSERT INTO HOIDONG (MSHD, PHONG, TGBD, NGAYHD, TINHTRANG, MSGV) VALUES
(5, 3, '08:00', '2014-11-30', N'Thật', 202);
REVERT;
GO