@startchen

' skinparam monochrome true
skinparam defaultFontName Iosevka
!pragma ratio 1.0
' skinparam roundcorner 10
skinparam dpi 300

entity DAILY {
'   MaDaiLy <<key>>
'   TenDaiLy
}

entity NHANVIEN {
'   MaNV <<key>>
'   TenNV
}

entity KHACHHANG {
'   MaKH <<key>>
'   TenKH
}

entity XE {
'   BienSo <<key>>
'   HangXe
}

entity HOPDONG {
'   SoHD <<key>>
'   NgayLap
}

entity THANHTOAN {
'   MaTT <<key>>
'   NgayTT
}

entity BAOHANH {
'   MaBH <<key>>
'   MoTaLoi
'   NgayBatDau
'   NgayKetThuc
}

entity LINHKIEN {
'   MaLK <<key>>
'   TenLK
'   Gia
}

relationship LAMVIEC {
'   NgayLamViec
}

relationship YEUCAUBAOHANH {
'   NgayYeuCau
}

relationship THUCHIENBAOHANH {
'   NgayThucHien
'   MaNV <<foreign>>
}

relationship DUOCBAOHANH {
'   NgayDuocBaoHanh
}

relationship TAOHD {
'   NgayTao
}

relationship DUYETHD {
'   NgayDuyet
}

relationship CHITIETHD {
'   SoLuong
'   DonGia
}

relationship CHITIETBAOHANH {
'   SoLuongLK
'   Giatien
}

relationship THONGTINTHANHTOAN {
'   MaTT <<foreign>>
'   SoTien
}

relationship MUAXE {
'   NgayMua
}

LAMVIEC -(1,1)- NHANVIEN
LAMVIEC -(1,n)- DAILY
YEUCAUBAOHANH -(1,n)- KHACHHANG
YEUCAUBAOHANH -(1,1)- BAOHANH
THUCHIENBAOHANH -(1,1)- NHANVIEN
THUCHIENBAOHANH -(1,n)- BAOHANH
DUOCBAOHANH -(1,n)- XE
DUOCBAOHANH -(1,1)- BAOHANH
TAOHD -(1,n)- NHANVIEN
TAOHD -(1,1)- HOPDONG
DUYETHD -(1,n)- NHANVIEN
DUYETHD -(1,1)- HOPDONG
CHITIETHD -(1,n)- HOPDONG
CHITIETHD -(1,1)- XE
CHITIETBAOHANH -(1,n)- BAOHANH
CHITIETBAOHANH -(1,1)- LINHKIEN
THONGTINTHANHTOAN -(1,1)- THANHTOAN
THONGTINTHANHTOAN -(1,3)- HOPDONG
MUAXE -(1,n)- KHACHHANG
MUAXE -(1,1)- HOPDONG

@endchen
