@startuml "Bai 2. Class Diagram"

''skinparam classAttributeIconSize 0
skinparam defaultFontName "Iosevka"

class DaiLy {
  # maDaiLy: string
  - viTri: string
  + themNhanVien()
  + xoaNhanVien()
  + themHopDong()
}

' --- Inheritance ---
abstract class NhanVien {
  # maNV: string
  - tenNV: string
  - chucVu: string
  + nhanChucVu()
}
class NVHanhChanh extends NhanVien {
  - trinhDoHocVan: string
  - phongBan: string
  + lapHopDong()
  + duyetHopDong()
}
class NVKyThuat extends NhanVien {
  - bacTho: string
  - soNamKN: int
  + thucHienBaoHanh()
}
' ------------------

class KhachHang {
  # maKH: string
  - tenKH: string
  - diaChi: string
  - sdt: string
  + muaXe()
  + yeuCauBaoHanh()
}

class HopDong {
  # soHD: string
  - ngayHD: Date
  - thoiGianBH: string
  - tienPhaiTT: float
  - tienDaTT: float
  - giamTru: float
  + themXe()
  + themPhieuThanhToan()
  + tinhTienConLai()
}

class Xe {
  # soKhung: string
  # soSuon: string
  - nuocSX: string
  - loaiXe: string
  + themTieuSuBaoHanh()
}

class PhieuThanhToan {
  # maPTT: string
  - ngayTra: Date
  - soTien: float
}

class BaoHanh {
  # maBH: string
  - ngayYeuCau: Date
  - soKhung: string
  - soSuon: string
  + themChiTietBaoHanh()
  + giaoChoNhanVien()
}

class LinhKien {
  # maLK: string
  - tenLK: string
}

' --- Association Class ---
class ChiTietBaoHanh {
  - lyDo: string
  - loiThuocVe: string
  - giaTien: float
  + themLinhKien()
}

' --- Associations ---
DaiLy "1" -- "0..*" NhanVien : "có"

KhachHang "1" -- "0..*" HopDong : "mua xe"
HopDong "0..*" -- "1" NVHanhChanh : "kế toán duyệt"
HopDong "0..*" -- "1" NVHanhChanh : "người lập"
HopDong "1" -- "1..*" Xe : "bao gồm xe"
HopDong "1" -- "1..3" PhieuThanhToan : "có phiếu thanh toán"
NVKyThuat "1" -- "0..*" BaoHanh : "thực hiện"

KhachHang "1" -- "0..*" BaoHanh : "yêu cầu bảo hành"
BaoHanh "1" -- "1..*" Xe : "bảo hành cho xe"
(BaoHanh, ChiTietBaoHanh) .. LinhKien
BaoHanh "1" -- "0..*" ChiTietBaoHanh: "nội dung công việc"
ChiTietBaoHanh -- "1..*" LinhKien: "sử dụng linh kiện"
@enduml
