@startchen "Bai 2. EER Diagram"

' ERD Chen notation khong ho tro Ke thua (Inheritance)
skinparam backgroundcolor transparent
skinparam defaultFontName "Iosevka"
!pragma layout neato

' --- Entities ---
entity DAILY {
  ' MaDaily <<key>>
  ' ViTri
}

entity PHONGBAN {
  ' MaPB <<key>>
  ' TenPB
}

relationship THUOC {
  'Phong Ban thuoc Dai Ly
}

DAILY -(1,n)- THUOC
PHONGBAN -(1,1)- THUOC

entity NHANVIEN {
  ' MaNV <<key>>
  ' TenNV
  ' ChucVu
}

relationship NV_PHONGBAN {
  ' Nhan Vien lam viec o Phong Ban
}
NHANVIEN -(1,1)- NV_PHONGBAN
PHONGBAN -(1,n)- NV_PHONGBAN

entity CHUCVU {
  ' MaCV <<key>>
  ' TenCV
}

relationship CHUCVU_NHANVIEN {
  ' Nhan Vien co Chuc Vu
}

NHANVIEN -(1,n)- CHUCVU_NHANVIEN
CHUCVU -(1,n)- CHUCVU_NHANVIEN

relationship CHUCVU_PHONGBAN {
  ' Chuc Vu thuoc Phong Ban
}

CHUCVU -(1,1)- CHUCVU_PHONGBAN
PHONGBAN -(1,n)- CHUCVU_PHONGBAN

entity KHACHHANG {
  ' MaKH <<key>>
  ' TenKH
  ' DiaChi
  ' SDT
}

entity HOPDONG {
  ' SoHD <<key>>
  ' NgayHD
  ' ThoiGianBH
  ' TienPhaiTT
  ' TienDaTT
  ' GiamTru
}

entity XE {
  ' SoKhung <<key>>
  ' SoSuon <<key>>
  ' NuocSX
  ' LoaiXe
  ' MauXe
  ' SoPK
}

entity PHIEUTHANHTOAN {
  ' MaPTT <<key>>
  ' NgayTra
  ' SoTien
}

entity BAOHANH {
  ' MaBH <<key>>
  ' NgayYeuCau
}

entity LINHKIEN {
  ' MaLK <<key>>
  ' TenLK
}

' --- Relationships ---
relationship LAM_TAI {
}

DAILY -(1,n)- LAM_TAI
NHANVIEN -(1,1)- LAM_TAI

relationship LAP_HD {
}

NHANVIEN -(1,n)- LAP_HD
HOPDONG -(1,1)- LAP_HD

relationship DUYET_HD {
  ' NV Ke Toan
}

NHANVIEN -(1,n)- DUYET_HD
HOPDONG -(1,1)- DUYET_HD

relationship MUA_HANG {
}

KHACHHANG -(1,n)- MUA_HANG
HOPDONG -(1,1)- MUA_HANG

relationship BAO_GOM {
  ' 1 HD co nhieu Xe
}

HOPDONG -(1,n)- BAO_GOM
XE -(1,1)- BAO_GOM

relationship TRA_GOP {
  ' 1 HD co max 3 PTT
}

HOPDONG -(1,3)- TRA_GOP
PHIEUTHANHTOAN -(1,1)- TRA_GOP

relationship YEUCAU_BH {
}

XE -(1,n)- YEUCAU_BH
BAOHANH -(1,1)- YEUCAU_BH

relationship THUCHIEN_BH {
  ' 1 BH co nhieu Chi Tiet Bao Hanh
}

BAOHANH -(1,n)- THUCHIEN_BH
NHANVIEN -(1,n)- THUCHIEN_BH

relationship CHITIET_BH {
  ' n-n giua BAOHANH va LINHKIEN
  ' LyDo
  ' LoiThuocVe
  ' GiaTien
}

BAOHANH -(1,n)- CHITIET_BH
LINHKIEN -(1,n)- CHITIET_BH

@endchen