@startchen "Bai 2. EER Diagram"

' ERD Chen notation khong ho tro Ke thua (Inheritance)
skinparam backgroundcolor transparent
skinparam defaultFontName "Iosevka"
!pragma layout neato

' --- Entities ---

entity DAILY {
  ' MaDaily <<key>>
  ' ViTri
}

entity PHONGBAN {
  ' MaPB <<key>>
  ' TenPB
}

entity NHANVIEN {
  ' MaNV <<key>>
  ' TenNV
  ' ChucVu
}

entity CHUCVU {
  ' MaCV <<key>>
  ' TenCV
}

entity KHACHHANG {
  ' MaKH <<key>>
  ' TenKH
  ' DiaChi
  ' SDT
}

entity HOPDONG {
  ' SoHD <<key>>
  ' NgayHD
  ' ThoiGianBH
  ' TienPhaiTT
  ' TienDaTT
  ' GiamTru
}

entity XE {
  ' SoKhung <<key>>
  ' SoSuon <<key>>
  ' NuocSX
  ' LoaiXe
  ' MauXe
  ' SoPK
}

entity PHIEUTHANHTOAN {
  ' MaPTT <<key>>
  ' NgayTra
  ' SoTien
}

entity BAOHANH {
  ' MaBH <<key>>
  ' NgayYeuCau
}

entity LINHKIEN {
  ' MaLK <<key>>
  ' TenLK
}

' --- Relationships ---

relationship CHUCVU_NV {
  ' Nhan Vien co Chuc Vu
}

NHANVIEN -(1,n)- CHUCVU_NV
CHUCVU -(1,n)- CHUCVU_NV

relationship CV_PB {
  ' Chuc Vu thuoc Phong Ban
}

CHUCVU -(1,1)- CV_PB
PHONGBAN -(1,n)- CV_PB

relationship NV_PB {
  ' Nhan Vien lam viec o Phong Ban
}
NHANVIEN -(1,1)- NV_PB
PHONGBAN -(1,n)- NV_PB

relationship PB_DAILY {
  'Phong Ban PB_DAILY Dai Ly
}

DAILY -(1,n)- PB_DAILY
PHONGBAN -(1,1)- PB_DAILY

relationship LAM_VIEC {
}

DAILY -(1,n)- LAM_VIEC
NHANVIEN -(1,1)- LAM_VIEC

relationship LAP_HD {
}

NHANVIEN -(1,n)- LAP_HD
HOPDONG -(1,1)- LAP_HD

relationship DUYET_HD {
  ' NV Ke Toan
}

NHANVIEN -(1,n)- DUYET_HD
HOPDONG -(1,1)- DUYET_HD

relationship MUA_HANG {
}

KHACHHANG -(1,n)- MUA_HANG
HOPDONG -(1,1)- MUA_HANG

relationship BAO_GOM {
  ' 1 HD co nhieu Xe
}

HOPDONG -(1,n)- BAO_GOM
XE -(1,1)- BAO_GOM

relationship TRA_GOP {
  ' 1 HD co max 3 PTT
}

HOPDONG -(1,3)- TRA_GOP
PHIEUTHANHTOAN -(1,1)- TRA_GOP

relationship YEUCAU_BH {
}

KHACHHANG -(1,n)- YEUCAU_BH
BAOHANH -(1,1)- YEUCAU_BH

relationship THUCHIEN_BH {
  ' 1 BH co nhieu Chi Tiet Bao Hanh
}


BAOHANH -(1,n)- THUCHIEN_BH
NHANVIEN -(1,n)- THUCHIEN_BH

relationship DUOC_BH {
  ' 1 Xe co the yeu cau bao hanh nhieu lan
  ' 1 Bao Hanh chi lien quan den 1 Xe
}

XE -(1,n)- DUOC_BH
BAOHANH -(1,1)- DUOC_BH

relationship CHITIET_BH {
  ' n-n giua BAOHANH va LINHKIEN
  ' LyDo
  ' LoiThuocVe
  ' GiaTien
}

BAOHANH -(1,n)- CHITIET_BH
LINHKIEN -(1,n)- CHITIET_BH

@endchen