@startuml

''skinparam classAttributeIconSize 0
skinparam defaultFontName "Iosevka"

class DaiLy {
  - maDaiLy: string
  - viTri: string
}

' --- Inheritance ---
abstract class NhanVien {
  # maNV: string
  # tenNV: string
  # chucVu: string
}
class NVHanhChanh extends NhanVien {
  - trinhDoHocVan: string
  - phongBan: string
}
class NVKyThuat extends NhanVien {
  - bacTho: string
  - soNamKN: int
}
' ------------------

class KhachHang {
  - maKH: string
  - tenKH: string
  - diaChi: string
  - sdt: string
}

class HopDong {
  - soHD: string
  - ngayHD: Date
  - thoiGianBH: string
  - tienPhaiTT: float
  - tienDaTT: float
  - giamTru: float
  + tinhTienConLai()
}

class Xe {
  - soKhung: string
  - soSuon: string
  - nuocSX: string
  - loaiXe: string
}

class PhieuThanhToan {
  - maPTT: string
  - ngayTra: Date
  - soTien: float
}

class BaoHanh {
  - maBH: string
  - ngayYeuCau: Date
}

class LinhKien {
  - maLK: string
  - tenLK: string
}

' --- Association Class ---
class ChiTietBaoHanh {
  - lyDo: string
  - loiThuocVe: string
  - giaTien: float
}

' --- Associations ---
DaiLy "1" -- "0..*" NhanVien : "có"

KhachHang "1" -- "0..*" HopDong : "mua"
HopDong "1" -- "1" NhanVien : "được lập bởi"
HopDong "1" -- "1" NhanVien : "được duyệt bởi (kế toán)"
HopDong "1" -- "1..*" Xe : "bao gồm"
HopDong "1" -- "1..3" PhieuThanhToan : "có"

Xe "1" -- "0..*" BaoHanh : "yêu cầu"
(BaoHanh, ChiTietBaoHanh) .. LinhKien
BaoHanh "1" -- "0..*" ChiTietBaoHanh
ChiTietBaoHanh -- "1..*" LinhKien
@enduml